### ISSUE TITLE
weird (?) behaviour of get_variables in `Reaction`

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/Catalyst.jl#422] opened 2021-09-26 09:53 UTC
as expected behavior if get_variables from symbolics on expression, with `t` being considered as variable
```julia
@variables t x y z(t)
ex = t*x + y + sin(z)
julia> Symbolics.get_variables(ex)
4-element Vector{Any}:
 y
 z(t)
 t
 x
```

but in reactions
```julia

@parameters k[1:2]
@variables t A(t) B(t) C(t) D(t)
rxs = [
              Reaction(k[1]*t, [A], [B]),                                # A -> B with non constant rate.
              Reaction(k[2]*t*A, [B,C], [D],[2,1],[2])                  # 2A +B -> 2C with non constant rate.
         ]
 @named rs = ReactionSystem(rxs, t, [A,B,C,D], k)
specs = species(rs)

julia>  deps = get_variables(rxs[1].rate,  specs)
Any[]

julia>  deps = get_variables(rxs[2].rate, specs)
1-element Vector{Any}:
 A(t)
```
why is `t` not considered as variables, despite assigning it as a variable with `@variables t A(t) B(t) C(t) D(t)`.
or is it expected to give output as such ?

This seems little worrisome considering role of get_variables in `graphs.jl` functions `Graphs` and `complexgraph`

eg.
```julia
rxs = [ Reaction(k[1]*t, [A], [B]),                                # A -> B with non constant rate.
                    Reaction(k[2], [A],[B]),   # A -> with constant rate
        Reaction(k[2]*t*A, [B,C], [D],[2,1],[2])                  # 2A +B -> 2C with non constant rate.
                ]
@named rs = ReactionSystem(rxs, t, [A,B,C,D], k)
Graph(rs)
```
![Screenshot from 2021-09-26 15-48-00](https://user-images.githubusercontent.com/26343789/134803759-14d1a8b4-878c-408f-b8eb-bb3223a6954c.png)

There are two reation from A to B, but no way to differentiate which is just dependent on parameters and which one on variable t

**Comment by yewalenikhil65** [comment] 2021-09-26 10:18
This seems little worrisome considering role of get_variables in `graphs.jl` functions `Graphs` and `complexgraph`

eg.
```julia
rxs = [ Reaction(k[1]*t, [A], [B]),                                # A -> B with non constant rate.
                    Reaction(k[2], [A],[B]),   # A -> with constant rate
        Reaction(k[2]*t*A, [B,C], [D],[2,1],[2])                  # 2A +B -> 2C with non constant rate.
                ]
@named rs = ReactionSystem(rxs, t, [A,B,C,D], k)
Graph(rs)
```
![Screenshot from 2021-09-26 15-48-00](https://user-images.githubusercontent.com/26343789/134803759-14d1a8b4-878c-408f-b8eb-bb3223a6954c.png)

**Comment by isaacsas** [comment] 2021-09-26 12:48
This is the expected behavior. `get_variables(ex, states)` returns the members of `states` that are within `ex`. If you want all the parameters/variables use `get_variables(ex)`. If you want species and time use `get_variables(ex, [species(rs); get_iv(rs)])`.

The graph is meant to show connections between species and reactions. `t` is not a species and so is not shown on the graph. I guess we could change the color / shape or add text within a reaction circle to indicate it has an explicit time-dependence, but at a certain point the information density in the graph makes it hard to interpret...

**Comment by yewalenikhil65** [comment] 2021-09-26 12:58
> The graph is meant to show connections between species and reactions. `t` is not a species and so is not shown on the graph. I guess we could change the color / shape or add text within a reaction circle to indicate it has an explicit time-dependence, but at a certain point the information density in the graph makes it hard to interpret...


I would like to think adding an extra colour to the edge with `explicit time dependence only` would not be too much of information, and also would not be Non-aesthetic

**Comment by isaacsas** [comment] 2021-09-26 13:12
I don't know why one would modify the edges; they indicate species a reaction's rate law depends on, and species produced by a reaction. This information is independent of whether there is an explicit time-dependence in the rate expression. If one is going to modify anything it seems to be it should be the little circle that represents a reaction node, changing it to indicate the rate has an explicit time-dependence through color, size, shape, or text within it (maybe putting a small `t` inside it?). If you want to PR such a change feel free!

**Comment by isaacsas** [comment] 2021-09-28 13:38
@yewalenikhil65 I'm going to close this since I think `get_variables` is working properly. Feel free to put in that PR though if you want to modify the reaction node when there is an explicit time dependence.

**Closed by isaacsas** 2021-09-28 13:38 UTC

**Comment by yewalenikhil65** [comment] 2021-11-12 08:34
@isaacsas , sorry, this is little old,but i think i have still found similar issue with `get_variables`your earlier comment,
> This is the expected behavior. `get_variables(ex, states)` returns the members of `states` that are within `ex`. If you want all the parameters/variables use `get_variables(ex)`. If you want species and time use `get_variables(ex, [species(rs); get_iv(rs)])`.
First quoting 
example,
```julia
@parameters k[1:3]
@variables t
@variables X[1:3](t)
rxs = [Reaction(k[1]/(X[1] + (1+X[3])*(1+X[2])), [X[1]], [X[2], X[3]],[1],[1,1]),
      Reaction(k[2]/(X[1] + (1+X[3])*(1+X[2])), [X[3], X[2]], [X[1]], [1,1], [1]),
      Reaction(k[3], [X[2], X[3]], [X[1]], [1, 1], [1]),
     ]

x = collect(X)
k = collect(k)
@named rs = ReactionSystem(rxs, t, x, k)
julia> get_variables(rxs[1].rate, species(rs))
Any[]

julia> get_variables(rxs[2].rate, species(rs))
Any[]

```
This still returns empty `Any vector`. Can you clarify on this please ?

**Comment by isaacsas** [comment] 2021-11-12 12:21
This is an issue with Symbolics.jl's current array handling and `get_variables` not having been updated there for it. You could add your example to the already open issue there: https://github.com/JuliaSymbolics/Symbolics.jl/issues/425
