### ISSUE TITLE
Converting Reaction network to ODEsystem issue

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/Catalyst.jl#269] opened 2020-10-23 20:28 UTC
Hi,
I think I am facing some problem with correctly converting a reaction network into ODESystsem using Catalyst. The coefficients of ODE's don't match with the expected system.
Following is the reaction system and expected ODE system,
```
k1,  A + B --> C
k2,  A --> 2C
k3,  2C --> A
```
expected ODESystem
```
A'(t) = -k1 A(t) B(t) - k2 A(t) + k3  [C(t)]^2
B'(t) =  -k1 A(t) B(t)
C'(t) = k1 A(t) B(t)  + 2 k2 A(t) - 2 k3 [C(t)]^2
```

Following is my julia code of reaction network and obtained ODESystem using `convert` function
```julia
rn = @reaction_network begin
    k1, A + B --> C
    k2, A --> 2*C
    k3, 2*C --> A
end k1 k2 k3

using Latexify
odesys = convert(ODESystem,rn)
print(latexify(odesys))

```

which gives ODEsystem output as,
![image](https://user-images.githubusercontent.com/26343789/97051126-457f8a80-159c-11eb-8351-edc0aadbca87.png)

**Comment by isaacsas** [comment] 2020-10-23 21:18
Isn't that consistent with how we define the rate laws? See

https://catalyst.sciml.ai/dev/tutorials/models/#Reaction-rate-laws-used-in-simulations

If you don't want the factorial terms I think doing
```julia
convert(ODESystem,rn, combinatoric_ratelaws=false)
```
should drop them.

**Comment by yewalenikhil65** [comment] 2020-10-23 21:34
Thanks, this works to get rid of factorial terms.
I was not aware of the reference also, thanks for sharing. Can you please let me know why factorial term arises ? I was only aware of following form of rate law which had no ffactorials in it.
This is from wikipedia page, https://en.wikipedia.org/wiki/Rate_equation
![image](https://user-images.githubusercontent.com/26343789/97055984-86c86800-15a5-11eb-80ab-23ea703cbea2.png)

**Comment by isaacsas** [comment] 2020-10-23 22:10
It's consistent with the stochastic interpretation, where the rate laws correspond to the probability per time one set of molecules can react multiplied by the number of possible combinations (see the same page). It ensures the ODEs are the essentially the mean-field of the stochastic jump process / chemical Langevin equation model.

The convention in the literature seems to vary on whether to include these terms or not. We should probably get a tutorial together that discusses this as right now the `combinatoric_ratelaws` flag is only shown in the ModelingToolkit docs.

**Comment by yewalenikhil65** [comment] 2020-10-31 17:14
Can I individually evaluate this `oderatelaw` at some particular time , if I have already solved a system of reactions ?
for example,
```julia
rn = @reaction_network begin
    k1, A + B --> C
    k2, A --> 2*C
    k3, 2*C --> A
end k1 k2 k3
x0 = Float32[rand(),rand(),0.0,0.0,0.0];
prob = ODEProblem(rn, x0, tspan, k)
sol = solve(prob, saveat = tsteps)

oderatelaw(rn.eqs[1]) # this gives me an 'Operation' of the rate law for first reaction.
```
Can I evaluate this `oderatelaw` from the `sol` obtained above at different time-instances?

**Comment by isaacsas** [comment] 2020-10-31 17:24
Right now I think you'd have to manually call the `oderatelaw` function, which gives you back a ModelingToolKit Expression, and then you'd have to use `build_function` to turn the expression into a function you can evaluate. I'll try to put an example together for you today or tomorrow. 

But more generally this is another good suggestion for us to add an API function for, and I'll add this to our TODO list!

**Comment by isaacsas** [comment] 2020-10-31 17:26
Just to clarify; what you've done is half-way there, you now need to use ModelingToolkit's [`build_function`](https://mtk.sciml.ai/dev/build_function/#build_function-1) to turn your `Operation` into a function you can call with the solution and parameter vectors.

**Comment by isaacsas** [comment] 2020-10-31 17:27
See also the first ModelingToolkit tutorial: https://mtk.sciml.ai/dev/tutorials/symbolic_functions/

**Comment by yewalenikhil65** [comment] 2020-10-31 17:34
Ok
Thanks for the reference, I will take a look and try doing this. The reason I asked this query is, we can easily write system of ODEs of chemical reaction systems as following. It would be nice for catalyst to have this capability for later
```julia
k1, A + B -->C
k2, A -->2C
k3, 2C -->A
```
written as
```
[dA/dt , dB/dt ,dC/dt] = 
 [-1 -1 1; -1 0 0; 1 2 -2] * diagonal([k1*A*B , k2*A, k3*(C^2)])

```
this diagonal matrix is fully of `oderatelaw` entries on this diagonal

**Comment by isaacsas** [comment] 2020-10-31 17:45
Yup! You can write a general system of ODEs as a sparse matrix for the stoichiometries times a vector of the rate laws. However, it isn't clear that will offer any performance benefit compared to our current approach (and using the matrix-vector form actually requires more memory storage since one needs a cache matrix and cache vector to store them). In fact, a while ago I tested in-place versions of that form which evaluate rate laws and add them into each equation in which they appear (following discussions with @ChrisRackauckas). I was hoping that by evaluating each rate law only once we might see a speed up, but I think that was compensated for by the non-sequential updating of `du` entries with those rate laws. I don't recall seeing any appreciable performance increase. Of course, in the matrix-vector form one would evaluate all the rate laws and then fill in the equations through matrix-vector multiplication, but I'm still not sure there would be a significant performance benefit.

**Comment by yewalenikhil65** [comment] 2020-10-31 17:55
Actually, I was not concerned about the performance issue, as I am assuming I have already solved the system(using Catalyst.jl, DifferentialEquations.jl) and then evaluating the `oderatelaw`.

I came across a method which aids in reducing the system of reactions, while still being able to approximate the full-system. (Kind of eliminating the unimportant reactions). This framework required expressing reaction system in above mentioned form, (Thought doing it manually every time for each reaction system might be tedious and even more for large systems). So I thought if I could do anything using Catalyst to automatically creating such form.

reference of the paper:
https://aip.scitation.org/doi/10.1063/1.5139463

**Comment by isaacsas** [comment] 2020-10-31 18:14
Cool, looks very interesting! Well, first step is for us to provide a simpler way to get back the `oderatelaw`s as Julia functions, so we'll definitely plan on adding such an API function. Hopefully using `build_function` works ok for you for now as a temporary approach.

**Comment by yewalenikhil65** [comment] 2020-10-31 21:03
`oderatelaw` returns an Operation, which has terms like `x1(t)` `x2(t)` and so on.. The term `t` is causing the trouble while using `build_function`

**Comment by yewalenikhil65** [comment] 2020-10-31 21:57
```julia
using Catalyst, SparseArrays

# rn is my reaction network as discussed before
nr = numreactions(rn)


D = sparse(SparseArrays.Diagonal([oderatelaw(rn.eqs[i]) for i in 1:nr]))
expr = build_function(D, t, [rn.states[i] for i in 1:nr] , [rn.ps[i] for i in 1:nr] )
myf = eval(expr[2])
out = zeros(Float32, nr, nr)
myf(out, sol.t[2] , sol[2], k)   # creating the D matrix at t = 2 using solution found from ODE
```

**Comment by yewalenikhil65** [comment] 2020-11-01 19:32
Hi @isaacsas 
I am beginning to feel, the `oderatelaw` should have better returned `Operation` in terms of `k1*x1^2` and not `k1*x1**(t)**^2`
This might have made usage of `build_function` much easier for evaluating them.
Currently, I think issue of 'not callable' is because of `(t)` part .

**Comment by isaacsas** [comment] 2020-11-01 20:01
@yewalenikhil65 You can look at `jumpratelaw` in the pre-4.0 ModelingToolkit to see how we got around that before, see 

https://github.com/SciML/ModelingToolkit.jl/blob/9e56519b6b82d2ab95524352fec79ff1a52241f5/src/systems/reaction/reactionsystem.jl#L258 

IIRC the `var2op` stuff is specifically to map `A(t)` to `A`.

However, and @shashi can confirm, I think this issue shouldn't be around in the latest ModelingToolkit (v4.0 and greater). That is a breaking release, so I still have to finish testing a few Catalyst features before we can put out a new Catalyst release that works with it. I'm hoping to get to it tonight after I finish making lectures for my class... So this issue might go away in a few days (though you'll need to make code updates as ModelingToolkit has changed the internal types to no longer use `Operation`s or `Variable`s).

**Comment by yewalenikhil65** [comment] 2020-11-01 20:23
@isaacsas Thank you :)
This is great(works perfect for jumprate) ! I think now it should easily work for `oderatelaw` with similar changes.

**Comment by yewalenikhil65** [comment] 2020-11-02 05:14
Hi @isaacsas 
I made following changes(currently using only as some user-defined function ) to the `oderatelaw` function. This seems to work. 
```julia
function myoderatelaw(rx;  rxvars=get_variables(rx.rate),combinatoric_ratelaw=true)
    @unpack rate, substrates, substoich, only_use_rate = rx
    rl = rate
    for op in rxvars
	rl = substitute(rl, op => var2op(op.op))
    end
    if !only_use_rate
        coef = one(eltype(substoich))
        for (i,stoich) in enumerate(substoich)
            coef *= factorial(stoich)
            rl   *= isone(stoich) ? var2op(substrates[i].op) : var2op(substrates[i].op)^stoich
        end
        combinatoric_ratelaw && (!isone(coef)) && (rl /= coef)
    end
    rl
end
```

**Comment by isaacsas** [comment] 2020-11-02 21:10
Let's see if this is still needed with Catalyst 6.0 -- this may be fixed in ModelingToolkit now.

**Comment by isaacsas** [comment] 2020-11-04 20:21
So this isn't fixed unfortunately on the new MT, however, you can get it to work without changing `oderatelaw` by following what is done here:
https://github.com/SciML/ModelingToolkit.jl/blob/1f35567f8c86b013798579bad7efb93a8cf53de0/src/systems/diffeqs/abstractodesystem.jl#L71-L79

Basically, you need to use `substitute` to replace the `Term`s like `A(t)` with a `Sym` `A(t)` and then `build_function` works. I'd prefer note to modify `oderatelaw` since my understanding is that `ODESystem`s assume the input will be in the form we generate through `oderatelaw` and not the substituted form. 

I'm going to close this here, but reopen the MT issue with your simpler example. It seems to me that `build_function` should be smarter and handle such substitution for one.

**Closed** 2020-11-04 20:21 UTC

**Comment by isaacsas** [comment] 2020-11-04 20:33
Actually, I think this works if you modify your `build_function` call:
```julia
f = build_function(a,[x1 ,x2, k1, k2], conv=ModelingToolkit.states_to_sym([x1,x2,k1,k2]))
```
Let me know if that fixes your issue.

**Comment by yewalenikhil65** [comment] 2020-11-05 20:23
Hi,
Currently `states_to_sym` yields error in my case. I think I do not have updated version of ModelingToolkit, I will update and try this soon.

**Comment by isaacsas** [comment] 2020-11-05 20:39
Keep in mind you'll need ModelingToolkit >=4.0 and Catalyst >=6.0, and these are breaking releases that may require you to change code. So I wouldn't update if what you're doing currently works for you or you don't have some time to tweak your scripts.

**Comment by yewalenikhil65** [comment] 2020-12-16 05:53
Hi @isaacsas  Thank you.
Just updating in case anybody stumbles upon this..
No need to change anything in `oderatelaw` now as i was doing earlier.. With Catalyst >=6.0 using `Term{Real}` instead of `Operation` , its as simple as doing the following

> ```
> Following code enables evaluating the rate laws
> 
> ```julia
> D = [oderatelaw(rn.eqs[i]) for i in 1:nr]
> expr = build_function(D, vcat([rn.states[i] for i in 1:ns], [rn.eqs[i].rate for i in 1:nr]))
> myf = eval(expr[2]);
> out = zeros(Float32, nr)
> myf(out, vcat(solution_vector , p))   # p is array of parameters of reaction rates
> # 'out' array contains evaluated oderatelaw from the solution and parameters
> ```
