### ISSUE TITLE
support general mass actions?

### ISSUE THREAD

**Issue by JianghuiDu** [SciML/Catalyst.jl#329] opened 2021-04-24 17:06 UTC
If I'm correct only rate law of the form [https://catalyst.sciml.ai/stable/tutorials/models/#Reaction-rate-laws-used-in-simulations](url) is supported, right? That seems two restrictive. I my field rate laws are almost never written in this format. Rather they are often completely empirical, derived from "fitting" experimental observations, and thus come in all kinds of forms. For example the mass action of `aA+bB=cC` may as well be `dA/dt = -k*[A][B]` or `k[A]/([A]+K)*[B]`rather than `dA/dt = -k*[A]^a[B]^b`. Is it possible to allow user supplied rate formats in the future?

**Comment by isaacsas** [comment] 2021-04-24 17:41
You can specify general functions of state as rate laws, see https://catalyst.sciml.ai/dev/tutorials/advanced/#User-defined-functions-in-reaction-rates

**Comment by JianghuiDu** [comment] 2021-04-24 19:13
I see your point. But then you have to write 3 reactions instead of 1? That balloons up very quickly. But thanks for the reminder.

**Comment by isaacsas** [comment] 2021-04-24 20:14
Why do you have to write three?

**Comment by JianghuiDu** [comment] 2021-04-25 07:26
Don't you need to do this?
```julia
k*[A][B], a*A→∅
k*[A][B], b*B→∅
k*[A][B], ∅→c*C


```

**Comment by isaacsas** [comment] 2021-04-25 16:53
Sorry, you wrote three different rate laws in your original post. What precise reaction are you trying to write, and what ODE models do you want to recover? You can't currently use parameters as stoichiometric coefficients if that is what you are asking about. You can use an arbitrary rate law for the whole reaction. So you can do
```
rn = @reaction_network begin
       k, 3*A + 5*B --> 2*C
end k a b c
```
or
```julia
rn = @reaction_network begin
       k/(A+K), A + B --> C
end k a b c
```
for specific values of the coefficients `a`, `b` and `c`.

**Comment by anandijain** [comment] 2021-04-25 16:56
i have no dog here, but it seems odd that you can't use parameters? what if you have control over a rxn rate?

**Comment by isaacsas** [comment] 2021-04-25 17:56
We'll get stoichiometry parameters eventually, perhaps even by modifying https://github.com/SciML/ModelingToolkit.jl/pulls

The issue, and it is an issue with that PR too, is that it is not clear how losing the concrete typing of stoichiometry vectors will affect performance for large systems. It may be a better design to have different reaction types when more generality is needed than to allow normal `Reaction`s to have stoichiometry vectors of type `Any`. Another concern is that using parameters means that even if your reaction is mass action it will not be realized as mass action for jump problems (i.e. becoming a ConstantRateJump instead of a MassActionJump), which has significant performance implications. We'd need another analysis layer in JumpProblem construction to avoid that.

That PR stalled since I need to play around it with and do some benchmarking, which I'm hoping to get to once the semester ends and my time frees up in a few weeks. Hopefully at that time we can look into more general functions for stoichiometry too.

**Comment by anandijain** [comment] 2021-04-25 18:03
You didn't link a PR?

**Comment by isaacsas** [comment] 2021-04-25 18:06
Yeah, that one.

**Comment by JianghuiDu** [comment] 2021-04-26 09:09
> Sorry, you wrote three different rate laws in your original post. What precise reaction are you trying to write, and what ODE models do you want to recover? You can't currently use parameters as stoichiometric coefficients if that is what you are asking about. You can use an arbitrary rate law for the whole reaction. So you can do
> 
> ```julia
> rn = @reaction_network begin
>        k, 3*A + 5*B --> 2*C
> end k 
> ```
> 
> or
> 
> ```julia
> rn = @reaction_network begin
>        k/(A+K), 3*A + 5*B --> 2*C
> end k K
> ```
> 
> for specific values of the coefficients `a`, `b` and `c`.

I might have confused you. I mean general mass actions rather than rate laws.
```julia
rn = @reaction_network begin
       k, 3*A + 5*B --> 2*C
end k 
```
gives 
![image](https://user-images.githubusercontent.com/31140772/116057126-c66c2b80-a67e-11eb-9b7f-251fd527ec2d.png)

If I disable the default mass action using `⇒`
```julia
rn = @reaction_network begin
       k, 3*A + 5*B ⇒ 2*C
end k 
```
I get
![image](https://user-images.githubusercontent.com/31140772/116057245-e865ae00-a67e-11eb-91e2-d4c736830c34.png)

However, what I want is 
![image](https://user-images.githubusercontent.com/31140772/116057726-5dd17e80-a67f-11eb-925c-17276745e8ff.png)

To achieve that, I need to break the reaction in to three and disable mass actions at the same time
```julia
rn = @reaction_network begin
       3k*A*B, A ⇒ ∅
       5k*A*B, B ⇒ ∅
       2k*A*B, ∅ ⇒ C
end k 
```

Is there a better way to do this? This approach kind of defeats the purpose of the DSL.

**Comment by JianghuiDu** [comment] 2021-04-26 09:17
> We'll get stoichiometry parameters eventually, perhaps even by modifying [SciML/ModelingToolkit.jl#942](https://github.com/SciML/ModelingToolkit.jl/pull/942)
> 
> The issue, and it is an issue with that PR too, is that it is not clear how losing the concrete typing of stoichiometry vectors will affect performance for large systems. It may be a better design to have different reaction types when more generality is needed than to allow normal `Reaction`s to have stoichiometry vectors of type `Any`. Another concern is that using parameters means that even if your reaction is mass action it will not be realized as mass action for jump problems (i.e. becoming a ConstantRateJump instead of a MassActionJump), which has significant performance implications. We'd need another analysis layer in JumpProblem construction to avoid that.
> 
> That PR stalled since I need to play around it with and do some benchmarking, which I'm hoping to get to once the semester ends and my time frees up in a few weeks. Hopefully at that time we can look into more general functions for stoichiometry too.

I didn't notice that parametric stoichiometry are not allowed. Another bummer for me since many of my chemical compounds are parametric like `C[m]H[n]O[p]` where `m,n,p` are parameters. One purpose of the reaction model is to fit those parameters.

**Comment by TorkelE** [comment] 2021-04-26 09:39
If I understand it right, currently a reaction>
N1*X1+N2*X2+... --> M1*Y1+M2*Y2+...
is interpreted
dX1/dt = -N1 * ([X1]^N1)/N1! * ([X2]^N2)/N2! + ...
dX2/dt = -N2 * ([X1]^N1)/N1! * ([X2]^N2)/N2! + ...
...
dY1/dt = M1 * ([X1]^N1)/N1! * ([X2]^N2)/N2! + ...
dY2/dt = M2 * ([X1]^N1)/N1! * ([X2]^N2)/N2! + ...

However, you are working in an application where you require the interpretation:
dX1/dt = -N1 *  [X1]*[X2]*...
dX2/dt = -N2 *  [X1]*[X2]*...
...
dY1/dt = M1 * [X1]*[X2]*...
dY2/dt = M2 * [X1]*[X2]*...
(possibly everything modified by some constant rate parameter)

Am I correct?


I have to admit, I have never seen you interpretation, had I been working with it myself when we implemented the tool I would probably have added it. Currently the only two ways we have to interpret and reaction is:
- Using normal mass action.
- Using the "ignore mass action" arrow option. We figured there might be a chance that someone would require some other interpretation we added this option. However, this functionality was designed for maximum flexibility (e.g. it could be used by people with yet different interpretations), not efficiency of use.

It would be possible to add another interpretation (like yours), and designate arrows for it. However, I think most people active on the package right now are currently busy, so I am not sure if you could expect such a feature to appear any time soon.

Out of curiosity, do you have some reference for this type of interpretation? What field exactly are you in which uses it?

**Comment by JianghuiDu** [comment] 2021-04-26 09:46
My background in in marine biogeochemistry and to be honest all the reactions I deal with have non-standard mass actions. The reason is that these reactions are macroscopic and observational reactions faked into microscopic molecular reactions. So the rate law/mass actions are entirely empirical. And it's a necessity out of simplification that we do this. Essentially, all the reactions are "catalyzed" by systems of biological communities. That's why it's not possible to use real molecular rate laws/mass reactions. I think this is very common in Earth and Environmental biogeochemistry.

**Comment by TorkelE** [comment] 2021-04-26 10:11
Makes sense.

I think we had some chat some time ago about generalizing reactions, but this I think is one of the first real examples (except for using non integer/stochastic stochiometric coefficients) that I have seen where this would be actually useful. It would be cool if one could define a function of a number of coefficients (for a number of substrates/products), supply this to Catalyst, and then this function would be used for defining a rate law.

Also, a side questions, I presume you (and other marine biochemists) only use deterministic models then? Or would you have some kind of SDE/Jump process for stochastic simulations?

**Comment by isaacsas** [comment] 2021-04-26 11:19
Doesn't this do what you want then?
```julia
rn = @reaction_network begin
              k*A*B, 3*A + 5*B ⇒ 2*C
       end k
```

I agree though, we need to add/allow for stoichiometry parameters. Data fitting is a very good reason to need them! Hopefully we'll have this by the end of May.

**Comment by yewalenikhil65** [comment] 2021-04-26 11:53
> I agree though, we need to add/allow for stoichiometry parameters. 

i hope in this case existing stoichiometry  functions based on constant stoichiometric, won't need a drastic revamp ?

**Comment by isaacsas** [comment] 2021-04-26 12:08
That’s the goal.

**Comment by JianghuiDu** [comment] 2021-04-27 19:13
> t this do

I thought the stoichiometry is also disabled when you disable the mass action. Cool that this works.

**Comment by isaacsas** [comment] 2022-03-03 18:53
https://github.com/SciML/Catalyst.jl/pull/488 adds parametric stoichiometry via directly building Reaction(...)s. So you can now use that once it merges (i.e. use the DSL for non-parametric reactions and just extend/add on the extra parametric reactions to the already built system -- making sure to also add on any new species or parameters).

The one caveat is that ModelingToolkit upconverts all parameters from integer to floating point if you pass a tuple of mixed types for the initial condition mapping. This then causes an error with factorial functions in the default rate law form. You can either use osys = convert(ODESystem, rn; combinatoric_ratelaws=false) or ODEProblem(rn, ...; combinatoric_ratelaws=false) to disable our rescaling of rate laws by these factors (which should avoid the issue for ODE systems). Alternatively, you can pass a tuple with just numbers for the parameters to ODEProblem, which bypasses ModelingToolkit looking at it (i.e. don't do (:A => 1.0, :n => 1) but do (1.0,1) consistent with the ordering reported by parameters(rn)). I'll add some examples in the HISTORY.md file once the PR gets merged.

I'm going to close this as I've got a new issue on getting this to work in the DSL too (which may take a while longer since it will entail a decent amount of changing around macro parsing code I think).

**Closed by isaacsas** 2022-03-03 18:53 UTC
