### ISSUE TITLE
on `reactionparammap` function

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/Catalyst.jl#449] opened 2021-11-13 04:16 UTC
according to  catalyst docs
> reactionparamsmap(network)
Given a ReactionSystem, return a Dictionary mapping from parameters that appear within Reactions to their index within `reactionparams(network)`.

Wouldn't it be more appropriate to map parameters to the index within `reactions(network)`, instead of `reactionparams(network)`? It would also make sense with current naming as it suggests at the first glance that it is mapping between reactions and parameters.
(I understand this was made to be consistent with the definitions of `speciesmap` and `paramsmap` functions)

**Comment by isaacsas** [comment] 2021-11-14 21:35
It gives the order within reactionparams, which is useful for compositional systems which may have non-ReactionSystem subsystems (so that reactionparams and parameters give different results).

**Comment by yewalenikhil65** [comment] 2021-11-16 15:18
This sounds new to me. Can you please point me in the direction of such an example, if it's in docs in sciml somewhere ?

**Comment by isaacsas** [comment] 2021-11-16 15:25
It isn't really documented since we aren't advertising it yet. You can look in the code and tests at the use of `constraints` in `ReactionSystem`s. This allows one to attach a set of algebraic or ODE equations to a `ReactionSystem`, and they will be considered part of the system. Similarly one can add algebraic or ODE subsystems to a `ReactionSystem`. 

The problem is by using these one can easily generate an overdetermined system which will give problems. We really need to add the ability to reduce the `ReactionSystem` via algebraic constraints (of which conservation laws are one example). Then this will be more useful.

**Comment by isaacsas** [comment] 2022-01-21 20:26
Closing as I think this was answered, but feel free to reopen if you still have questions!

**Closed by isaacsas** 2022-01-21 20:26 UTC
